### ISSUE TITLE
Error upon import of scqubits

### ISSUE THREAD

**Issue by PhilippAumann** [scqubits/scqubits#112]
When importing ``scqubits`` after a fresh install, I get the error:
```python
ModuleNotFoundError: No module named 'h5py'
```
when running
```python
import scqubits
```
The error can be fixed easily by installing`h5py` by hand via 
```bash
conda/pip install h5py
```
After installing h5py, scqubits works without error.

I have tested this with python version 3.9.6

To reproduce the error, you could create a new conda environment with
```bash
conda create --name environment_name 
```
activate the environment and install scqubits
```bash
pip install scqubits
```
and run
```python
import scqubits
```
I don't know why pip doesn't install `h5py` since it's listed as a requirement in `setup.py`.

**Comment by petergthatsme** [comment]
Thanks for the report, I will take a look. 
A quick note, however. We typically discourage installing scqubits via pip under conda... usually a safer/better approach would be to do:
`conda install -c conda-forge scqubits  `
Does that not work for you? 
(As a side note, I think we may not have added python 3.9 as officially supported yet though, so i'm not sure what conda install does when trying to install a package without official support...  - either way we should probably do that soon)

**Comment by PhilippAumann** [comment]
I usually try to avoid mixing `pip` with `conda`. However for python 3.9, an installation via conda as you suggested, returns the following error:
```bash
UnsatisfiableError: The following specifications were found
to be incompatible with the existing python installation in your environment:

Specifications:

  - scqubits -> python[version='>=3.6,<3.7.0a0|>=3.8,<3.9.0a0|>=3.7,<3.8.0a0']

Your python: python=3.9
```
I guess this will change once u add python 3.9 as officially supported. Don't know if this solves the original issue though.

**Comment by petergthatsme** [comment]
Thanks for checking... 
Will include adding 3.9 as officially support as a high priority item, as it seems more and more people are using it these days. 
Will also check why h5py does not get installed automatically.

**Comment by jkochNU** [comment]
Both pytests on github and azure explicitly draw in the `optional-requirements.txt`. This is currently done because it includes `pytest` - but it also includes other optional dependencies such as `h5py`. It is thus possible that tests currently miss that I/we could have accidentally turned ``h5py into a required dependency the way imports are handled.

**TODO**
- determine whether we want to keep `h5py` optional
   - if so, restructure imports in `scqubits` with the necessary switches (some already in place for `h5py` as was intended)
- restructure dependency handling in setup for pytests to accurately reflect the environment found by a user installing `scqubits` in a brand new environment

**Comment by jkochNU** [comment]
Confirmed: `h5py` was accidentally imported without the needed switch [in `fileio.py`; import was introduced as part of type checking]. This should now be fixed with https://github.com/scqubits/scqubits/commit/73932dd9182eb8c5b26ebc1c04460da5084133e1.

**Comment by PhilippAumann** [comment]
The import works now without an error with python 3.9. Thank you!
