### ISSUE TITLE
[Suggestion/request] Permit branch parameters to be entered as Inductance/Capacitance/Ic

### ISSUE THREAD

**Issue by QuantumWitness** [scqubits/scqubits#146]
Would be nice to be able to define branch parameters using the physical value of the circuit element. That is to say, inductance for inductors, capacitance for capacitors, and junction critical current for junctions. 

Why?
1. Physical simulation software (Ansys, FastHenry, COMSOL) will report results using these units, and physical simulation is a critical part of the circuit design process.
2. Fabrication facilities usually define their junction process using two parameters, critical current density, $J_c$ (uA/um<sup>2</sup>), and junction specific capacitance, $c_j$ (in units of fF/um).
3. Min/max width limits in a fabrication facility will determine junction sizes, which are almost always referred to in units of critical current. 

I realize pretty much all of the literature refers to these circuit elements in the energy formalism, but day-to-day work often requires thinking in inductance, capacitance, and critical current units.

**Comment by jkochNU** [comment]
@QuantumWitness That's a fine suggestion and reminder that physics is not just what happens in a theorist's head.
I can see a solution to this with two components:

1. provide a helper function that does unit conversion to frequency units
2. extend parsing of yaml descriptions to include numbers with units attached (& internally employ 1 to go back to frequency units)

Internally, use of alternative units should be strictly limited to the yaml and the helper function. (No overloading of existing functions etc.)

**Comment by QuantumWitness** [comment]
I think that makes sense, and I believe that users should be OK with scqubits internals purely using frequency units, and it will be good for them to start thinking in this way, as well. 

Some more options for units:
1. set a global scqubits flag for units for each type of circuit element, so the YAMLs remain unchanged in formatting.
2. add a 'header' line to the YAML that specifies the units so that you can add functionality to look for that line and then parse the rest of the YAML without worrying about handling the various kinds of attached units?

**Comment by calebjordan** [comment]
As a circuit designer who has to bounce back and forth between physical simulation (ANSYS, etc) and Hamiltonian simulations, I second this request. We think in capacitances and critical currents, and allowing physical units instead of energy units would be very useful. 

Additionally, I would suggest sticking to standard [SPICE netlist syntax](https://eee.guc.edu.eg/Courses/Electronics/ELCT503%20Semiconductors/Lab/spicehowto.pdf#:~:text=Spice%20netlist%20is%20usually%20organized%20into%20different%20parts.,either%20left%20blank%2C%20or%20starts%20with%20a%20%E2%80%98%2A%E2%80%99%28asterik%29.) as much as possible, rather than developing a new one. This could allow for compatibility with other simulator tools, and is also quite scalable as it allows for nesting of components through sub-circuits, which may be useful for composite and multi-qubit systems.
