### ISSUE TITLE
[Bug report] Custom circuit with no inductances

### ISSUE THREAD

**Issue by MFMFMFMFMF** [scqubits/scqubits#155]
### Describe the bug
I was trying to make circuits with only JJ ands capacitances using the Custom circuit.  As there is no harmonic basis in that case i used the discretized version but i couldn't get the eigenvalues of the circuit.

### Expected behavior
To minimize misunderstandings, please state briefly what you expected to happen.

### To Reproduce
```python
transmon_circuit =  """# Transmon Circuit
branches:
- ["JJ", 0,1, EJ={0},EC ={1}]
""".format(EJ,EC0)
transmon = Circuit.from_yaml(transmon_circuit, from_file=False, ext_basis="discretized")

transmon.sym_hamiltonian()
```
$\displaystyle 4.0 EC Q_{1}^{2} + - EJ \cos{\left(θ_{1} \right)}$

```python
transmon_circuit =  """# Transmon Circuit
branches:
- ["JJ", 0,1, EJ={0},EC =0]
- ["C", 0,1,{1}]
""".format(EJ,EC0)
transmon = Circuit.from_yaml(transmon_circuit, from_file=False, ext_basis="discretized")

transmon.sym_hamiltonian()
```
$\displaystyle 4.0 EC Q_{1}^{2} + - EJ \cos{\left(θ_{1} \right)}$

The second circuit gives me am error as : 
```python 

File ~\AppData\Roaming\Python\Python39\site-packages\scqubits\core\circuit.py:1424, in Subsystem._replace_mat_mul_operator(self, term)
   1422 def _replace_mat_mul_operator(self, term):
-> 1424     if not self._is_mat_mul_replacement_necessary(term):
   1425         return str(term)
   1427     if self.ext_basis == "discretized":

File ~\AppData\Roaming\Python\Python39\site-packages\scqubits\core\circuit.py:1419, in Subsystem._is_mat_mul_replacement_necessary(self, term)
   1416 def _is_mat_mul_replacement_necessary(self, term):
   1417     return (
   1418         set(self.var_categories["extended"])
-> 1419         & set([get_trailing_number(str(i)) for i in term.free_symbols])
   1420     ) and "*" in str(term)

AttributeError: 'int' object has no attribute 'free_symbols'
```

### OS and version used (please complete the following information):
 - OS:  windows
 - scqubits version 3.0.0
 - Python version 3.9.12

### Additional context
Any additional information you would like to provide to aid us.
I tried adding a spurious inductance of very low energy for example as : 
```python
transmon_circuit =  """# Transmon Circuit
branches:
- ["JJ", 0,1, EJ={0},EC =0]
- ["C", 1,0,{1}]
- ["L", 0,1,Eeps]
```

but this creates two issues. it adds a flux and also the frequencies do not match even as the added term to the hamiltonian at zero flux becomes negligible.

**Comment by jkochNU** [comment]
Thanks for posting this!
For part 1: The default for circuits without linear inductances is charge basis. @saipavanc Is discretization even expected to work in that case? If not, then we should issue an exception

For part 2: are you saying you are inductively shunting a Cooper pair box / transmon? The L->0 limit is highly singular and should **not** yield the CPB/transmon spectrum, see https://journals.aps.org/prl/abstract/10.1103/PhysRevLett.103.217004. If I am misunderstanding your point, please follow up with some more clarification.

**Comment by MFMFMFMFMF** [comment]
>

**Comment by MFMFMFMFMF** [comment]
For part 2: I meant that i added a negligible inductive energy and not a negligible inductance.

(sorry for the wrong manipulation with the issue closing)

**Comment by jkochNU** [comment]
For part 2: my bad, I meant to write L -> \infty and went wrong. It is the L-> \infty limit that is discussed in the paper I quoted. As I said, the limit is singular (you cannot go continuously from L2-integrability boundary conditions to periodic boundary conditions), and the spectrum will not converge to that of a CPB/transmon.

**Comment by saipavanc** [comment]
@MFMFMFMFMF I have a few questions about the following input file that you have written.
```
transmon_circuit =  """# Transmon Circuit
branches:
- ["JJ", 0,1, EJ={0},EC =0]
- ["C", 0,1,{1}]
""".format(EJ,EC0)
transmon = Circuit.from_yaml(transmon_circuit, from_file=False, ext_basis="discretized")
```
Here, you are setting `EC`, which is the capacitance energy, to zero. But, this would imply that the capacitance is basically set to infinity, and no matter how big or small a capacitor you add in parallel, it would only give you infinite capacitance. Thus, there is not kinetic energy term in the resultant Hamiltonian. This is what is causing trouble, as one of the strings which corresponds to the kinetic energy is rendered to be an empty string, which should not cause any trouble as such and I will fix it in the very next commit. 

But, I am guessing that this is not what you were trying to do. If you want to set the capacitance in the junction to be zero, then you should set its capacitance energy to a very high value,  like in this input file. 

```
transmon_circuit =  """# Transmon Circuit
branches:
- ["JJ", 0,1, EJ={0},EC =1e15]
- ["C", 0,1,{1}]
""".format(EJ,EC0)
transmon = Circuit.from_yaml(transmon_circuit, from_file=False, ext_basis="discretized")
```
And the above code gives me results as I would expect. Let me know if this is what you were trying to do. Also, we have updated scqubits to a new version 3.0.3 which changes the way symbolic expressions are printed. I recommend that you upgrade to the latest release.

Also regarding the parameter `ext_basis`, as @jkochNU was referring to, the parameter is used to set the basis for the extended variables in the Circuit. Since, there are no extended variables in the Circuit that setting would not affect any of the numerical calculations.

**Comment by MFMFMFMFMF** [comment]
yes perfect thank you so much for your answer
