### ISSUE TITLE
HilbertSpace contains both `subsystem_list` and `subsys_list`

### ISSUE THREAD

**Issue by nikosavola** [scqubits/scqubits#160]
### Describe the bug
Currently, HilbertSpace in [scqubits\core\hilbert_space.py](https://github.com/scqubits/scqubits/blob/master/scqubits/core/hilbert_space.py#L455) contains two functions implementing the same thing, `subsystem_list` and `subsys_list`. The other returns a tuple and the ensures a list, but they are functionally the same.

### Expected behavior
Having duplicates is unnecessary unless there is some legacy deprecation going on.

**Comment by jkochNU** [comment]
`HilbertSpace` underwent multiple rounds of refactoring, and this is likely an accidental artefact of that. 
Additionally, despite its name, `subsystem_list` actually hands back a tuple instead of a list which is problematic on a separate level.

All changes here will need to start out with deprecation warnings. These properties/methods are probably not heavily used as `HilbertSpace` can be used as an iterable over subsystems. Nonetheless, changes may break user code. 

My suggestion: phase out both of the above in favor of a simple `<HilbertSpace>.subsystems` property that hands back the subsystems in tuple form.  @petergthatsme There are various other options, let me know what you prefer.

**Comment by jkochNU** [comment]
This is addressed by https://github.com/scqubits/scqubits/pull/174/commits/093a265e330ea47ba88b88c7cd339688d9529ffa which initiates deprecation of  `subsys_list` in favor of `subsystem_list` (consistent with methods/attributes including `subsystem_count`).
