### ISSUE TITLE
Short tutorial video on using scqubits

### ISSUE THREAD

**Issue by petergthatsme** [scqubits/scqubits#184]
We ask that you make a short (4-6 minutes) tutorial video about some aspects of using scqubits. This video could include going through and explaining one of the tutorial notebooks that have already been written (see [here](https://github.com/scqubits/scqubits-examples/tree/master/examples) for examples), or alternatively creating a custom notebook and explaining what it does. 

Some examples of what such a video would look like are shown [here](https://www.youtube.com/watch?v=XB8-RA_F90A) or [here](https://www.youtube.com/watch?v=baBQy1IUOJE).

Good candidates for notebooks to discuss would be:  
[demo_qutip_fluxoniumreset.ipyn](https://github.com/scqubits/scqubits-examples/blob/master/examples/demo_qutip_fluxoniumreset.ipynb)
[demo_qutip_fluxoniumcz.ipynb](https://github.com/scqubits/scqubits-examples/blob/master/examples/demo_qutip_fluxoniumcz.ipynb)
[scqubits_paper_source_code.ipynb](https://github.com/scqubits/scqubits-examples/blob/master/examples/scqubits_paper_source_code.ipynb)
[demo_customcircuit.ipynb](https://github.com/scqubits/scqubits-examples/blob/master/examples/demo_customcircuit.ipynb)

Alternatively putting together a "custom" notebook that includes some new discussion that we don't yet cover, or even some combination of what's already been done would also be great. An example might be a notebook that explores performing a gate operation on a noisy transmon qubit (such a notebook would include parts of content presented in [here](https://github.com/scqubits/scqubits-examples/blob/master/examples/demo_transmon.ipynb) and [here](https://github.com/scqubits/scqubits-examples/blob/master/examples/demo_noise.ipynb)).

Specific requirements:  

- Choose a scqubits tutorial notebook from [here](https://github.com/scqubits/scqubits-examples/tree/master/examples) or alternatively write your own - it could be some combination of content from ones that already exist. 

- Reply with a comment to this bounty that includes a few sentences (could be in point-form, i.e., a sentence per section in the notebook you want discuss) that outlines what your tutorial would cover and what which aspects of the code and relevant physics you aim to highlight.

- Put together a 4-6 minute video

- Either upload the video to youtube and provide a link to it. Alternatively provide a link to where the video could be downloaded from (e.g. dropbox). In the latter case, please explicitly write that you agree that we upload your video to the the @scqubits youtube channel.

**Comment by KevinJoven11** [comment]
Dear Peter,

I want to work on this video. My idea to cover is the following:

* Explain the circuit quantization procedure.
* Give the procedure to quantize any circuit (step by step given the in the Quantum Information & Quantum Optics by Juan Jose Ripoll). Starting with the differential equation, find the Lagrangian and the Hamiltonian, and finally, give the common examples from the LC oscillator and the transmon (C+JJ).

* Show the ability to scqubits to calculate and give any *custom_circuit* quantization. Show the same equation given theoretically.
* Show & explain the scqubits GUI to finally encourage people to try the library.

My idea is to do a custom notebook that explains and covers this topic step by step, explaining how to design in scqubits. Let me know if this is enough or if you have more ideas to include. 
Time constraints? I think the video will be longer than the 4-6 min (4-6 min explaining the theory and 4-6 min explaining scqubits). Is there a problem with having a longer video?

Best,
Kevin J.

**Comment by petergthatsme** [comment]
Hi Kevin... what you propose sounds great!
As far as the length of the video - I would propose splitting the video into two parts... each about 4-6 mins long - that seems to work better with people's short attention spans (just a reality of things these days  ;-), but also might make them easier to make. 
If you feel rather strongly about a single longer one, however, that would also be fine.
The rest of what you propose reads great - picking custom circuits is a perfect candidate for tutorial videos - good choice!

Please let us know if you have any other questions.

**Comment by Algh89110377** [comment]
Hi Kevin, 
Can I also work on the videos? I am also interested in making tutorial videos.

**Comment by ZhaoTianPu** [comment]
> Hi Kevin,
> Can I also work on the videos? I am also interested in making tutorial videos.

Hi Alireza, just to help clarify, are you interested in collaborating with Kevin to make tutorial videos or you would like work on video(s) by yourself?

**Comment by Algh89110377** [comment]
We can work together.

**Comment by KevinJoven11** [comment]
Hi Alireza, thanks for your interest in collaborating with scqubits and me! 
I already have the two presentations about quantum circuit quantization, and I am planning to record them this weekend. If you already have a video in mind I will absolutely be happy to work with you if not we can come up with another idea using scqubtis; more is better! You can reach me at https://www.linkedin.com/in/kevin-joven/

**Comment by Algh89110377** [comment]
Hi Kevin,
I added you on Linkedin. Here is mine https://www.linkedin.com/in/ali-ghasemi-46404a87/ 
We can discuss this more on LinkedIn.

**Comment by hrahman12** [comment]
> Hi Kevin,
> 
> I added you on Linkedin. Here is mine https://www.linkedin.com/in/ali-ghasemi-46404a87/ 
> 
> We can discuss this more on LinkedIn.
> 
> 

Hi I'd also like to work on this! Do let me know!

**Comment by KevinJoven11** [comment]
Dear Peter,

I already upload the videos as "unlisted". Please check the videos and let me know what you think to put the videos to the public. Let me know if there are things that need to be corrected, I will do it as quickly as possible. Also, I would like to read the comments from Tianpu Zhao & Alireza if possible.

Thanks!

Quantum Circuit Quantization Part 1 - Theory: https://youtu.be/ChefdJWovYc
Quantum Circuit Quantization Part 2 - scQubits: https://youtu.be/Tv3nLKb66OE

Best,
Kevin J.

**Comment by petergthatsme** [comment]
Thanks @KevinJoven11. 
Will get back to you in a day or two (but from a quick glance, they look great!)

**Comment by petergthatsme** [comment]
btw, @KevinJoven11  will you want to have these uploaded to the scqubits channel (https://www.youtube.com/@scqubits4175/videos ), or to your own? either would be fine.

**Comment by KevinJoven11** [comment]
Dear Peter, 

I am okay with both. Just let me know what you prefer!

Best,
Kevin J.

**Comment by ZhaoTianPu** [comment]
Hi Kevin,

Your videos look really nice. Thank you very much for your effort! I like the idea to start with studying the quantum version of the LC resonator in the first video, then shows how to model LC resonator and transmon with the Circuit module. I think these videos can certainly be further polished and improved, but your work might already be qualified for claiming the bounty (it's up to Jens/Peter's decision). 

Here are things I think could be improved. Maybe for some of these points you might have your own considerations/justifications, I would really love to hear your thoughts as well!

For the first video:
- The title "quantum circuit quantization": "quantum circuit" is ambiguous in the field of quantum computing - quantum circuit often refers to quantum computation models (those wires and boxes diagram you often see in quantum algorithms); for circuits made of superconducting metals, "superconducting circuit" is more frequently used.
- I think the derivation for the quantum LC oscillator can be streamlined for a better clarity. In your presentation, you started with expressing energies stored in a capacitor and an inductor, and wrote H(I, V) = CV^2/2 + LI^2/2, then you expressed I and V in terms of Phi and Phi dot and wrote H(Phi, Phi dot). Both are not the correct form of Hamiltonian, since Hamiltonian should be written in terms of pairs of conjugate variables (n and Phi in our case). I saw you later presented the general procedure (starting from differential equation, write down Lagrangian, then perform Legendre transformation to obtain Hamiltonian, then promote conjugate variables to quantum operators); why don't you start with using these steps to build the LC circuit Hamiltonian at the beginning?
- As far as I know, the common practice for circuit quantization starts from writing down the Lagrangian, rather than writing down the differential equation.
- You also have a slides titled "working at ~mK" in the middle of your LC oscillator example. I feel like it'd be better discussed at the beginning, since I think these points are motivations for us to use superconducting circuits at ~ mK as qubits. Also the point "no resistance" can help answer why we usually only model circuits with L, C and Josephson junctions.
- You have a slide talking about Josephson junctions. I feel like the motivation for discussing Josephson junctions is missing there. I noticed that in the second video you did talk about anharmonicity is needed for obtaining a qubit and therefore we need nonlinear elements. Maybe it would be better to briefly mention in this slide that nonlinear inductance is crucial for making qubits.
- Inductor symbol: I usually saw inductor symbols are curly lines (and there are many variants of them). Is the square lines in your slides another commonly used inductor symbol?

For the second video:
- The content generally looks great!
- The screen capture seems quite blurred and I can barely read - would be much better if the video has higher resolution.

**Comment by petergthatsme** [comment]
Thanks again @KevinJoven11 for working on the videos, and thanks @ZhaoTianPu for your comments. 

@KevinJoven11, if you have it in you to address some of the comments from @ZhaoTianPu, that would of course be great, but since we know that these sorts of videos take a long time to make, we are also fine accepting them as-is, as far as the bounty goes. 

As far as publishing them, what might be best, is if you could make them publically available on your channel, and maybe leave a link somewhere where the source files could be downloaded from (so that down the road, if it makes sense, Jens could also put them up on the @scqubits channel). 

Agh.. and one suggestion: at least for the second video, maybe make sure that "scqubits" is mentioned somewhere in the title, so that the video is easier to find via youtube's search machinery.

thanks

**Comment by KevinJoven11** [comment]
Dear Peter,
Thanks for your feedback and to Tianpu Zhao as well!
I already made the video for public and put in the title scQubits and anyone can download the repo from the link in the video below.
I am planing to improve the videos as well.
Thank you so much,
Kevin J.

**Comment by petergthatsme** [comment]
Thanks @KevinJoven11 
We can consider this bounty as closed then.

**Comment by ZhaoTianPu** [comment]
Hi Alireza, thank you so much for your contributions. Your video looks really nice! I will make time today to watch it and provide my thoughts/suggestions. 

I am not sure if you can get the bounty at this time (I hope you will be able to, based on what you've worked)! This would be better answered by @petergthatsme.

**Comment by petergthatsme** [comment]
Thanks for your work on the video @Algh89110377   - it's very nice. Please feel free to make it public.

A couple of minor points: 
- could you please update the title of the video so that it contains "scqubits"? that will make it easier for people to find. 
- could you please update the video description with a couple of sentences that describe what the video is about, and ideally, with a link to the very notebook you're going over

I asked the powers that be at the Unitary Fund, and it looks like they will be able to award both you and @KevinJoven11   with the rewards - which is great (thanks Unitary Fund!).

**Comment by ZhaoTianPu** [comment]
@KevinJoven11 after discussing with colleagues I hope to correct myself: it is ok to talk first about equations of motion, then the Lagrangian and Hamiltonian. As long as the Euler-Lagrange equation obtained from Lagrangian agrees with the equations of motion, then it is fine.

**Comment by KevinJoven11** [comment]
Dear @ZhaoTianPu ,
Thank you so much for your feedback! In the future, I will explain this tutorial more deeply as soon as I have more experience working with superconducting circuits!
Best,
Kevin
