### ISSUE TITLE
[Bug report] Parameter sweep may (?) not be correctly updating parameters during a scan

### ISSUE THREAD

**Issue by petergthatsme** [scqubits/scqubits#209]
parameter sweep may potentially not be properly updating parameters during scans - see worksheet:
https://github.com/scqubits/scqubits-examples/blob/master/examples/demo_parametersweep.ipynb

**Comment by saipavanc** [comment]
Can confirm the issue, when using `deepcopy=True`, in the first ParameterSweep object defined about. Might have been introduced when I changed `copy.deepcopy(sweep)` to `dill.loads`. Not sure why this does not work, will look into it.

**Comment by saipavanc** [comment]
@petergthatsme It took a little while to sort this out, the problem was how the `subsys_update_info` was defined and used internally. We are using the actual qubit instances to define  `subsys_update_info`, but after a deep copy or cloning of the instance, we no longer have the same instance in the `ParameterSweep._hilbertspace` anymore. Instead of looking for the same subsystem in the provided list, the recent commit uses the `id_str` of the qubit instances to make the comparison. Which makes sense even when the instances are copied. 5421a07 seems to fix the issue.
