### ISSUE TITLE
[Other issue] Confusion in coherence time calculation.

### ISSUE THREAD

**Issue by sirshisram** [scqubits/scqubits#212]
Hello! 

I was trying to replicate the coherence times reported in PRX 11, 011010 (2021) with the following lines of code `fluxonium = scq.Fluxonium(EJ = 9.0, EC = 2.5, EL = 0.52, flux = 0.5, cutoff = 110, truncated_dim = 4)`
`print(r'T1:',fluxonium.t1_effective(total=True, common_noise_options=dict(T=0.00019))*(1e-3),' us')`
`print(r'T2:',fluxonium.t2_effective(common_noise_options=dict(T=0.00019))*(1e-3), ' us')`

This is what I get: `T1: 4445.823719536628 us`, `T2: 2910.6219635808525 us`. I immediately checked the documentation page for [Calculations and Visualizations](https://scqubits.readthedocs.io/en/latest/guide/noise/ipynb/visualization.html#Effective-coherence-time-calculations) and it says that the times are given in units of the system units (which I have set to GHz). But going over here - [scqubits.Fluxonium.t1_effective](https://scqubits.readthedocs.io/en/latest/_generated/scqubits.Fluxonium.t1_effective.html#scqubits.Fluxonium.t1_effective), it says that the decoherence times are given in units of angular frequency, which means that I'll need to multiply a factor of 2pi. This results in unrealistic coherence times (like 27ms or so).

Please help me in this regard.

**Comment by petergthatsme** [comment]
Thanks for your question. I think maybe the doc strings are confusing; you do not have to multiply by factors of 2pi to get the coherence times in natural units. To be concrete, the thing that the `t1` or `t2`/`tphi` methods of scqubits spit out is the inverse rate that would normally go directly into a master equation. 

So to give a specific example: let's say we're looking at two lowest levels of a fluxonium circuits - that's our qubit, and we care about some t1 type decay process. The effective master equation of such a system would read (setting hbar=1): 

$$ \dot ρ = -i [ 2 \pi (\frac{E_q}{2}) \sigma_z, ρ ]  + T_1^{-1} D[\sigma_{-}]ρ $$

where E_q would be the energy splitting between the two lowest levels, and 1/T_1 the corresponding downwards decay rate. 

One could obtain E_q from sqcubits, and by default it would assume that all the energies, and thus the reported E_q, are given in GHz. Furthermore, the obtained T_1 (through `t1_XXX` type methods) would be be in nanoseconds. 

(Note, to just get the downward-only contribution required for this example, the relevant t1 based method should get `total=False` passed in). 

Hope things are clearer now. I will add it to our list to make the doc strings reflect this better. 

Note also that in your example you have: 

`print(r'T1:',fluxonium.t1_effective(total=True, common_noise_options=dict(T=0.00019))*(1e-3),' us')`

you would want to put the `total=True` into the `common_noise_options` dictionary, as `t1_effective` would not process it otherwise (here it doesn't actually matter as `total=True` is the default for all the `t1_XXX` methods that `t1_effective` calls, anyway).

**Comment by sirshisram** [comment]
Thank You @petergthatsme for your response. Things are a bit clearer now.

**Comment by sirshisram** [comment]
But a small question, why does the Fluxonium times seem to be high as per scqubits? Why am I unable to replicate the values that PRX 11, 011010 (2021) reports?

**Comment by petergthatsme** [comment]
can you send the code you're using to try to replicate their numbers? one thing to point out would be that perhaps some of the deafult parameters that go into those calculations (e.g. quality factots, noise strenghts, etc) that scqubits uses, may not be identical to what the paper assumes. Hence one might have to exlicitily set the values taken from the paper.

**Comment by sirshisram** [comment]
Like, in calculating the relaxation from flux noise:

```python

h = 6.62606957e-34 
h_bar = h/2*np.pi
e = 1.6e-19 #C
flux_quantum = h/(2*e)
k_B = 1.3806488e-23 

### RELAXATION FROM FLUX NOISE ###
R_q = h/e**2
R = 26
M = 625 
temp = 0.042
beta = 1/(k_B*temp)
L = 1257.4e-9

def flux_noise_spectral_density(omega):
    spect = (np.pi**3)*(h_bar**2)*(R_q/R)*(M**2/L**2)*omega*(1/np.tanh(beta*h_bar*omega/2))
    return spect

fluxonium.t1(1, 0, fluxonium.phi_operator(), flux_noise_spectral_density, 0.042)
```

I get 6.112e+33 ns.

For 1/f flux noise: 

```python
def one_f_flux_noise_spectral_density(omega):
    #spect = 8*(np.pi**3)*(fluxonium.EL**2)*((5.21e-6)**2)/omega
    spect = 2*np.pi*(5.21e-6*flux_quantum)**2/omega
    return spect

fluxonium.t1(1, 0, fluxonium.phi_operator(), one_f_flux_noise_spectral_density, 0.042)

```

I am getting infinity. (paper reports 2.4ms)

For chargeline noise: 

```python

Q_c = 7.4e4 #R_q/(16*np.pi*R)

def chargeline_noise_spectral_density(omega):
    spect = (omega/Q_c)*(1/np.tanh(beta*h_bar*omega/2))
    return spect

fluxonium.t1(1, 0, fluxonium.n_operator(), chargeline_noise_spectral_density, 0.042)
```

I am getting 0.2894 ns (the paper reports 10us)

Please correct me. Where am I going wrong?

**Comment by petergthatsme** [comment]
I've only had a very quick chance to glance at the paper, but here are a few comments:

### t1 capacitive/inductive noise

to reproduce those from fig 3 in the paper, one could run something like:

```
fluxonium = scq.Fluxonium(EJ = 3.395, EC = 0.479, EL = 0.132, flux = 0.5, cutoff = 210, truncated_dim = 6)

fig, ax = fluxonium.plot_coherence_vs_paramvals(
                     param_name='flux',
                     param_vals=np.linspace(0.25, 0.5, 25),
                     noise_channels = [('t1_capacitive', dict(Q_cap=1/(4e-6)))],
                     common_noise_options=dict(T=0.042),
                     label = "t1_capacitive",
                     scale=1e-6,
                    color='red',
                    linestyle='--'
                    );

fluxonium.plot_coherence_vs_paramvals(
                     param_name='flux',
                     param_vals=np.linspace(0.25, 0.5, 25),
                     noise_channels = [('t1_inductive', dict(Q_ind=8e9))],
                     common_noise_options=dict(T=0.042),
                     label = "t1_inductive",
                     scale=1e-6,
                    color='green',
                    linestyle='--',
                    fig_ax = (fig, ax)
                    );
ax.set_title("")
ax.set_ylabel(r"$T_1$($ms$)")
ax.set_xlabel(r"$\Phi_x/\Phi_0$")
ax.set_ylim(1e-1, 2e1)
ax.legend()
```
which results in something like:
![plot1](https://github.com/scqubits/scqubits/assets/4156234/9373fd03-1650-4d1b-bc6c-33c90bdecae6)

### purcell t1

scqubits does not include the type of calculation that's done in the paper for a purcell t1 (i.e. from appendix G5); that could be done "manually", or alternatively one define an appropriate S(omega), which would be related to the admittance of the oscillator circuit that their fluxonium couples to, shown in fig 1b. At some stage we will provide an explicit example of how this can be done in the docs somewhere. 
 
### 1/f flux dephasing 

note that scqubits currently does not implement a tphi from 1/f noise obtained via an echo type experiment, so this is something you'd have to do manually (using results from the Ithier paper, for example) in order to reproduce fig 3b (also worth pointing out that there seems to be a typo in their x label - should probably have a factor of 1e-4 and not 1e4). 

we do provde a 1/f calculation for 1/f Ramsey type experiment, and that could be for by something along the lines of:
```
fig, ax = fluxonium.plot_coherence_vs_paramvals(
                     param_name='flux',
                     param_vals=np.linspace(-0.05, 0.05, 51),
                     noise_channels = ['tphi_1_over_f_flux'],
                     label = "tphi_1_over_f_flux",
                     scale=1e-3,
                    ylabel=r"$\mu$",
                    xlabel=r"$\Phi_x/\Phi_0$",
                    color='red',
                    linestyle='--'
                    );
ax.set_ylabel(r"$T_{\phi}$($\mu s$)")
ax.set_ylim(1, 3e1)
ax.legend()
```

it's worth pointing out, however, that currently we only calculate the leading order correction, resulting in a zero rate at the optimal point (flux=0.5 here, befause the qubit-energy flux dervative is zero there)... so that's why the tphi value will go into infinity at this flux point. We hope to add a 2nd order correction in the next version of scqubits. 

### other; your manual calculations. 

I haven't tried to run your code, but you seem to have a bug in how you define hbar: should read `hbar = h/(2*pi)` and not `hbar = h/2*pi`. So maybe try to fix that and look for other typos, and let me know if you still have issues.

**Comment by sirshisram** [comment]
Thank you so much for the detailed response. I'll close this issue.
