### ISSUE TITLE
[Bug report] xlabel and ylabel are exchanged on the skyscraper matrix function

### ISSUE THREAD

**Issue by dkweiss31** [scqubits/scqubits#90]
when calling `scqubits.utils.plotting.matrix` with the options to set the xlabel, ylabel and xticklabels, yticklabels, these are exchanged from one plot to the other. I believe the layout for the matrix plot on the right is correct, while the skyscraper plot is incorrect. See the attached figure for an illustration of the bug.

![image](https://user-images.githubusercontent.com/32396142/102442370-e1040900-3fe9-11eb-8c2e-c43cb4d52a89.png)
Any additional information you would like to provide to aid us.

**Comment by jkochNU** [comment]
@dkweiss31 Please provide:
1. More explicit info on what the bug is (right now I’m left to guess without sufficient context)
2. Minimal code example to reproduce the issue

**Comment by dkweiss31** [comment]
Sure - here is a MWE
```
import numpy as np
import matplotlib.pyplot as plt

from scqubits.utils.plotting import matrix

mat = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])
x_labels = ['a', 'b', 'c']
y_labels = ['d', 'e', 'f']
fig, (ax1, ax2) = matrix(mat, show_numbers=True, xlabel='X',
                         ylabel='Y', xticklabels=x_labels,
                         yticklabels=y_labels)
plt.show()
```
which should produce the below figure (I didn't notice that the first x_label and y_label element get cut off as well, which is not expected). If I'm not mistaken, looking at the two figures, the axes are incorrectly labeled on the skyscraper plot.
![image](https://user-images.githubusercontent.com/32396142/102443955-9ab0a900-3fed-11eb-8013-4911749fbe3f.png)

**Comment by petergthatsme** [comment]
thanks for the example Danny. I fixed the labels offset (and also generalized the skyscraper plots to non-square matrices similarly to what can be done with matrix2d plots, in case that is useful for something in the future)

There is a minor subtlety as far as i can see, related to how we define the x and y axis. In the matrix2d type plots (on the right in your example), we define the horizontal direction as the x-axis that increase to the right, and the vertical direction as the y-axis that increase towards the bottom (as far as the xlabel, and ylabel keyword arguments are concerned). By the right-hand-rule, that defines the positive z axis as "into the page"... Of course that doesn't matter as far as a flat matrix2d plot is concerned, but it does matter in a skyscraper plot (on the left), which may seem inverted if one thinks that the positive direction in the matrix2d plot should be "out of page". As far as I can see what we're doing now is the right thing, but please reopen this if you think otherwise. 

Closing for now.
